[phases.setup]
aptPkgs = [
  "gcc", "g++", "build-essential",
  "libsndfile1", "ffmpeg", "rubberband-cli"
]

[phases.install]
cmds = [
  "pip install --no-cache-dir 'numpy==1.23.5' 'Cython==3.0.11' 'scipy==1.11.4'",
  "pip install --no-cache-dir --no-build-isolation 'madmom==0.16.1'",
  "pip install --no-cache-dir -r requirements.txt"
]
